services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - USER_PASSW=${USER_PASSW}

  frontend:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_ENVIRONMENT=${VITE_ENVIRONMENT}

  db:
    image: postgres:15
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: prueba-ifx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
